name: piaxiverse
channels:
  - defaults
dependencies:
  - asttokens
  - backcall
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - contourpy
  - cryptography
  - cycler
  - cyrus-sasl
  - daal4py
  - dal
  - decorator
  - dill
  - executing
  - expat
  - fontconfig
  - fonttools
  - freetype
  - giflib
  - glib
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - ipython
  - jedi
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libdeflate
  - libevent
  - libffi
  - libllvm14
  - libpng
  - libpq
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpi
  - multiprocess
  - munkres
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - parso
  - pathos
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - ply
  - pooch
  - pox
  - ppft
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - pytz
  - qt-main
  - qt-webengine
  - qtwebkit
  - requests
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - setuptools
  - sip
  - six
  - sqlite
  - stack_data
  - tbb
  - threadpoolctl
  - tk
  - toml
  - tornado
  - tqdm
  - traitlets
  - tzdata
  - urllib3
  - wcwidth
  - wheel
  - xz
  - zlib
  - zstd
